baseURL = 'https://stephendltg.netlify.app'
title = "Stephen Deletang"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true


[params]
author = "stephendltg"
description = "Stephendltg's personal website"
keywords = "blog,developer,personal"
info = ["", "Developper backend & DevOps"]
avatarURL = "https://avatars.githubusercontent.com/u/10052911"
footerContent = "SHOPOPOP"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = "November 15, 2021"
commit = "https://github.com/stephendltg/mysite/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = false


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/stephendltg/"

[[params.social]]
name = "Twitter"
icon = "fa fa-twitter"
weight = 3
url = "https://twitter.com/stephendltg/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/stephen-deletang/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Works"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Hobbies"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 4
url = "contact/"
